### ISSUE TITLE
Pact V3 Tracking Issue

### ISSUE THREAD

**Issue by JP-Ellis** [pact-foundation/pact-python#396]
## :memo: Background

Pact Python at present makes use of the Ruby executables. The main functionality of the Ruby executables has been replaced by a core library written in Rust ([pact-foundation/pact-reference](https://github.com/pact-foundation/pact-python)).  This library exposes a foreign function interface which other languages can leverage without the need to re-implement a lot of the logic. The core library helps to maintain parity across the different clients and helps with the adoption of new features.

## :arrow_heading_up: Migration Plan

This change will introduce some breaking changes where needed, but it will be done in a staged manner to give everyone the opportunity to migrate.

### :construction: Stage 1 (from `v2.2`)

- The main Pact Python library remains the same. Bugs and minor features will continue to be added to the existing library, but no new major features will be added as the focus will be on the new library.
- The new library is exposed within `pact.v3` and can be used alongside the existing library. During this stage, no guarantees are made about the stability of the `pact.v3` module.
- Users are **not** recommended to use the new library in any production critical code at this stage, but are encouraged to try it out and provide feedback.
- The existing library will raise [`PendingDeprecationWarning`](https://docs.python.org/3/library/exceptions.html#PendingDeprecationWarning) warnings when it is used (if these warnings are enabled).

### :hammer_and_wrench: Stage 2 (from `v2.4`, tbc)

- The library within `pact.v3` is considered generally stable and users are encouraged to start migrating to it.
- A detailed migration guide will be provided.
- The existing library will raise [`DeprecationWarning`](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) warnings when it is used to help raise awareness of the upcoming change.
- This stage will likely last a few months to give everyone the opportunity to migrate.

### :rocket: Stage 3 (from `v3`)

- The `pact.v3` module is renamed to `pact`
  - People who have previously migrated to `pact.v3` should be able to do a `s/pact.v3/pact/` and have everything work.
  - If the previous stage identifies any breaking changes as necessary, they will be made at this point and a detailed migration guide will be provided.
- The existing library is moved to the `pact.v2` scope.
  - :bangbang: This will be a very major and breaking change. Previous code running against `v2` of Pact Python will **not** work against `v3` of Pact Python.
  - Users still wanting to use the `v2` library will need to update their code to use the new `pact.v2` module. A `s/pact/pact.v2/` should be sufficient.
  - The `pact.v2` module will be considered deprecated, and will eventually be removed in a future release. No new features and only critical bug fixes will be made to this part of the library.

## ✅ Tasks

- [x] #384
- [x] #397
- [x] #399
- [x] #382
  - [x] #418 
  - [x] #419 
- [x] #420 
  - [x] #473 
  - [x] #474
  - [x] #475 
  - [x] #476
- [x] #381 
- [x] #421
  - [x] #469 
  - [x] #470
  - [x] #471 
  - [x] #472
- [x] #380 
  - [x] [`v3/message_consumer.feature`](https://github.com/pact-foundation/pact-reference/blob/master/compatibility-suite/pact-compatibility-suite/features/V3/message_consumer.feature)
  - [x] [`v4/message_consumer.feature`](https://github.com/pact-foundation/pact-reference/blob/master/compatibility-suite/pact-compatibility-suite/features/V4/message_consumer.feature)
- [x] #379 
  - [x] [`v3/message_provider.feature`](https://github.com/pact-foundation/pact-reference/blob/master/compatibility-suite/pact-compatibility-suite/features/V3/message_provider.feature)
  - [x] [`v4/message_provider.feature`](https://github.com/pact-foundation/pact-reference/blob/master/compatibility-suite/pact-compatibility-suite/features/V4/message_provider.feature)
- [x] #378 
- [x] #746
  - [x] #759
  - [x] #1179
  - [x] #1180
- [x] #747
  - [x] #1181
  - [x] #1182
  - [x] #1183
- [x] #748
- [x] #749
- [ ] #377 
  _This may be covered in HTTP consumer/provider implementation above_
- [x] #376 
- [x] #375 
- [x] #374 
- [x] #373 
- [ ] Implement synchronous message compatibility suite:
  - [ ] [`v4/synchronous_message_consumer.feature`](https://github.com/pact-foundation/pact-reference/blob/master/compatibility-suite/pact-compatibility-suite/features/V4/synchronous_message_consumer.feature)
  - [ ] [`v4/v4.feature`](https://github.com/pact-foundation/pact-reference/blob/master/compatibility-suite/pact-compatibility-suite/features/V4/v4.feature)
- [ ] #372 
- [x] #1082 
- [x] Stabilise and announce `pact.v3`, release `v2.3` of Pact Python
  - [x] Replace `PendingDeprecationWarning` with `DeprecationWarning`
- [x] #383
- [x] #1222
- [x] Release Pact Python `v3`

## 🔗 Prior/Related Work

This change has been a long time coming:

- #357
  #366
  #367

  These PRs are all quite large, especially the last with 177 commits and 6.7k lines added. These PRs form the prior attempts to migrate Pact Python to make use of Rust library. While I would have loved to take #367 on and add to it, I think there's too much in there for a single PR.
  
  Having said that, a lot of the work done will be re-used in the tasks above.

- #234

  Migrating away from the Ruby executable will resolve this issue.

- #243

  Supplanted by this issue

- #245
  #265

  Additional (and very early) PRs with some work on implementing the FFI.

- #88
 
  A very early issue detailing the need to implement the FFI core.

**Comment by JP-Ellis** [comment]
Today, I decided to finally release Pact Python `v3.0.0`. While there are a couple of outstanding items in the above list, I believe some of these can be implemented in future releases.

As such, I am closing this ticket, and will create a new tracking issue for any new issues discovered as v3 is adopted:

- #1272
